### ISSUE TITLE
Emoticon icon packs - please provide one of the blobs ...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [kevalpatel2106/EmoticonGIFKeyboard#2]
Many users prefer them than those of the new Android O emojis.
Just look at the amount of love they got, from both developers and users:
https://issuetracker.google.com/issues/62256231
https://issuetracker.google.com/issues/38440592
And of course all the articles about them...

**Comment by kevalpatel2106** [comment]
@AndroidDeveloperLB Sure!!! I will release a different icon pack for old android emoticons.👍 Stay tuned for updates here.

**Comment by AndroidDeveloperLB** [comment]
Thank you!

**Comment by kevalpatel2106** [comment]
@AndroidDeveloperLB Added new emoticons icon packs in [v1.1](https://github.com/kevalpatel2106/EmoticonGIFKeyboard/releases/tag/v1.1).

- [Android 7.0 emoticons](https://github.com/kevalpatel2106/EmoticonGIFKeyboard/tree/master/emoticonpack-android7)

**Comment by AndroidDeveloperLB** [comment]
It has all the lovely blobs emojis ?
I also wonder: Are they SVG and/or VectorDrawable ?

**Comment by kevalpatel2106** [comment]
@AndroidDeveloperLB Yes, it contains all blobs.🙂 The images are in png/jpg.

**Comment by AndroidDeveloperLB** [comment]
Good.
Is it possible to have them alson in SVG and/or VectorDrawable?

**Comment by kevalpatel2106** [comment]
@AndroidDeveloperLB Yes . You can convert those PNGs to SVG/Vector if you  want.

**Comment by AndroidDeveloperLB** [comment]
I'm not aware of a good solution for this conversion. Was hoping there is an SVG version of these icons that Google has published somewhere
