### ISSUE TITLE
Library does not compile

### ISSUE THREAD

**Issue by vicpinm** [kevalpatel2106/EmoticonGIFKeyboard#3]
Is needed any special configuration with your library? It does not compile when I add the dependency to my project:

![image](https://user-images.githubusercontent.com/15379383/30016689-781c3538-9156-11e7-9eeb-ee84155efe57.png)

**Comment by kevalpatel2106** [comment]
@vicpinm This library is compiled with Java 8. So you need to make your project use Java 8. Add below lines to your module level `build.gradle`.

```groovy
compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}
```

**Comment by AdeelTariq** [comment]
@kevalpatel2106 I think this only works in Android studio versions 3.0 which is still in beta. Also as a side note are there any pro-guard settings needed for this library?

**Comment by kevalpatel2106** [comment]
@AdeelTariq Yes, Java 8 is currently supported in AS 3.0 only. I used some lambda expressions in the library. I will try to make library working on Java 7. Stay tuned for the upcoming release.
Also, proguard configurations are added inside the library itself. No need to add it manually.

**Comment by kevalpatel2106** [comment]
@vicpinm @AdeelTariq Java 7 support added in [v1.1](https://github.com/kevalpatel2106/EmoticonGIFKeyboard/releases/tag/v1.1).
